# Generated by Django 6.0.3 on 2026-03-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Класс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('file', models.FileField(upload_to='generated_pdfs/%Y/%m/', verbose_name='PDF')),
                ('include_answers', models.BooleanField(default=False, verbose_name='С ответами')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDF-файлы',
                'ordering': ['variant_number'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_tasks', to='assignments.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_assignments', to='tasks.task')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('assignment', 'task')},
            },
        ),
    ]
