# Generated by Django 6.0.3 on 2026-03-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Отправлена на модерацию'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('revision', 'Возвращена на доработку')], max_length=15, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запись модерации',
                'verbose_name_plural': 'Журнал модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
